// Jakar.Database :: Jakar.Database
// 02/03/2026  14:11

namespace Jakar.Database;


public interface IDbTable : IConnectableDb
{
    FusionCacheEntryOptions? Options          { get; set; }
    public ITableMetaData    PropertyMetaData { [Pure] get; }
    public string            TableName        { [Pure] get; }
}



public interface IDbTable<TSelf> : IDbTable
    where TSelf : PairRecord<TSelf>, ITableRecord<TSelf>
{
    RecordGenerator<TSelf> Records { get; }


    IAsyncEnumerable<TSelf>                   All( CancellationToken                                                  token = default );
    IAsyncEnumerable<TSelf>                   All( NpgsqlConnection                                                   connection, NpgsqlTransaction?                                            transaction, [EnumeratorCancellation] CancellationToken token = default );
    ValueTask<TResult>                        Call<TResult>( string                                                   sql,        PostgresParameters                                            parameters,  Func<SqlMapper.GridReader, CancellationToken, ValueTask<TResult>> func, CancellationToken token = default );
    ValueTask<TResult>                        Call<TResult>( NpgsqlConnection                                         connection, NpgsqlTransaction                                             transaction, string sql, PostgresParameters parameters, Func<SqlMapper.GridReader, CancellationToken, ValueTask<TResult>> func, CancellationToken token = default );
    ValueTask<TResult>                        Call<TResult>( SqlCommand<TSelf>                                        sql,        Func<NpgsqlDataReader, CancellationToken, ValueTask<TResult>> func,        CancellationToken token = default );
    ValueTask<TResult>                        Call<TResult>( NpgsqlConnection                                         connection, NpgsqlTransaction                                             transaction, SqlCommand<TSelf> command, Func<NpgsqlDataReader, CancellationToken, ValueTask<TResult>> func, CancellationToken token = default );
    ValueTask                                 Schema( Func<DataTable, CancellationToken, ValueTask>                   func,       CancellationToken                                             token                                                                        = default );
    ValueTask                                 Schema( Func<DataTable, CancellationToken, ValueTask>                   func,       PostgresCollectionType                                        collectionName, CancellationToken token                                      = default );
    ValueTask                                 Schema( Func<DataTable, CancellationToken, ValueTask>                   func,       PostgresCollectionType                                        collectionName, string?[]         restrictionValues, CancellationToken token = default );
    ValueTask<DataTable>                      Schema( NpgsqlConnection                                                connection, CancellationToken                                             token                                                                        = default );
    ValueTask<DataTable>                      Schema( NpgsqlConnection                                                connection, PostgresCollectionType                                        collectionName, CancellationToken token                                      = default );
    ValueTask<DataTable>                      Schema( NpgsqlConnection                                                connection, PostgresCollectionType                                        collectionName, string?[]         restrictionValues, CancellationToken token = default );
    ValueTask<TResult>                        Schema<TResult>( Func<DataTable, CancellationToken, ValueTask<TResult>> func,       CancellationToken                                             token                                                                        = default );
    ValueTask<TResult>                        Schema<TResult>( Func<DataTable, CancellationToken, ValueTask<TResult>> func,       PostgresCollectionType                                        collectionName, CancellationToken token                                      = default );
    ValueTask<TResult>                        Schema<TResult>( Func<DataTable, CancellationToken, ValueTask<TResult>> func,       PostgresCollectionType                                        collectionName, string?[]         restrictionValues, CancellationToken token = default );
    ValueTask<string>                         ServerVersion( CancellationToken                                        token = default );
    ValueTask<int>                            Execute( NpgsqlConnection                                               connection, NpgsqlTransaction transaction, string sql, PostgresParameters parameters, CancellationToken token );
    ValueTask<ErrorOrResult<TSelf>>           Last( CancellationToken                                                 token                                                               = default );
    ValueTask<ErrorOrResult<TSelf>>           Last( NpgsqlConnection                                                  connection, NpgsqlTransaction? transaction, CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           LastOrDefault( CancellationToken                                        token                                                                                                                                                                                                                            = default );
    ValueTask<ErrorOrResult<TSelf>>           LastOrDefault( NpgsqlConnection                                         connection, NpgsqlTransaction?                         transaction, CancellationToken                          token                                                                                                             = default );
    IAsyncEnumerable<TSelf>                   Where( bool                                                             matchAll,   PostgresParameters                         parameters,  [EnumeratorCancellation] CancellationToken token                                                                                                             = default );
    IAsyncEnumerable<TSelf>                   Where( string                                                           sql,        PostgresParameters                         parameters,  [EnumeratorCancellation] CancellationToken token                                                                                                             = default );
    IAsyncEnumerable<TSelf>                   Where<TValue>( string                                                   columnName, TValue?                                    value,       [EnumeratorCancellation] CancellationToken token                                                                                                             = default );
    IAsyncEnumerable<TSelf>                   Where( NpgsqlConnection                                                 connection, NpgsqlTransaction?                         transaction, string                                     sql,      PostgresParameters                         parameters, [EnumeratorCancellation] CancellationToken token = default );
    IAsyncEnumerable<TSelf>                   Where( NpgsqlConnection                                                 connection, NpgsqlTransaction?                         transaction, bool                                       matchAll, PostgresParameters                         parameters, [EnumeratorCancellation] CancellationToken token = default );
    IAsyncEnumerable<TSelf>                   Where( NpgsqlConnection                                                 connection, NpgsqlTransaction?                         transaction, SqlCommand<TSelf>                          command,  [EnumeratorCancellation] CancellationToken token = default );
    IAsyncEnumerable<TSelf>                   Where( SqlCommand<TSelf>                                                command,    [EnumeratorCancellation] CancellationToken token                                                                                                                               = default );
    IAsyncEnumerable<TSelf>                   Where<TValue>( NpgsqlConnection                                         connection, NpgsqlTransaction?                         transaction, string                                     columnName, TValue? value, [EnumeratorCancellation] CancellationToken token = default );
    IAsyncEnumerable<RecordID<TSelf>>         WhereID( bool                                                           matchAll,   PostgresParameters                         parameters,  [EnumeratorCancellation] CancellationToken token                                                                                                             = default );
    IAsyncEnumerable<RecordID<TSelf>>         WhereID( string                                                         sql,        PostgresParameters                         parameters,  [EnumeratorCancellation] CancellationToken token                                                                                                             = default );
    IAsyncEnumerable<RecordID<TSelf>>         WhereID<TValue>( string                                                 columnName, TValue?                                    value,       [EnumeratorCancellation] CancellationToken token                                                                                                             = default );
    IAsyncEnumerable<RecordID<TSelf>>         WhereID( NpgsqlConnection                                               connection, NpgsqlTransaction?                         transaction, string                                     sql,      PostgresParameters                         parameters, [EnumeratorCancellation] CancellationToken token = default );
    IAsyncEnumerable<RecordID<TSelf>>         WhereID( NpgsqlConnection                                               connection, NpgsqlTransaction?                         transaction, bool                                       matchAll, PostgresParameters                         parameters, [EnumeratorCancellation] CancellationToken token = default );
    IAsyncEnumerable<RecordID<TSelf>>         WhereID( NpgsqlConnection                                               connection, NpgsqlTransaction?                         transaction, SqlCommand<TSelf>                          command,  [EnumeratorCancellation] CancellationToken token = default );
    IAsyncEnumerable<RecordID<TSelf>>         WhereID( SqlCommand<TSelf>                                              command,    [EnumeratorCancellation] CancellationToken token                                                                                           = default );
    IAsyncEnumerable<RecordID<TSelf>>         WhereID<TValue>( NpgsqlConnection                                       connection, NpgsqlTransaction?                         transaction, string columnName, TValue? value, [EnumeratorCancellation] CancellationToken token = default );
    ValueTask<long>                           Count( CancellationToken                                                token                                                               = default );
    ValueTask<long>                           Count( NpgsqlConnection                                                 connection, NpgsqlTransaction? transaction, CancellationToken token = default );
    ValueTask<bool>                           Exists( bool                                                            matchAll,   PostgresParameters parameters,  CancellationToken token );
    ValueTask<bool>                           Exists( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, bool              matchAll, PostgresParameters parameters, CancellationToken token );
    IAsyncEnumerable<TSelf>                   Get( IEnumerable<RecordID<TSelf>>                                       ids,        CancellationToken  token                               = default );
    IAsyncEnumerable<TSelf>                   Get( IAsyncEnumerable<RecordID<TSelf>>                                  ids,        CancellationToken  token                               = default );
    ValueTask<ErrorOrResult<TSelf>>           Get( bool                                                               matchAll,   PostgresParameters parameters, CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           Get( string                                                             columnName, object?            value,      CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           Get( RecordID<TSelf>                                                    id,         CancellationToken  token                                                                                                                                     = default );
    ValueTask<ErrorOrResult<TSelf>>           Get( RecordID<TSelf>?                                                   id,         CancellationToken  token                                                                                                                                     = default );
    IAsyncEnumerable<TSelf>                   Get( NpgsqlConnection                                                   connection, NpgsqlTransaction? transaction, IAsyncEnumerable<RecordID<TSelf>> ids,        [EnumeratorCancellation] CancellationToken token                               = default );
    IAsyncEnumerable<TSelf>                   Get( NpgsqlConnection                                                   connection, NpgsqlTransaction? transaction, IEnumerable<RecordID<TSelf>>      ids,        [EnumeratorCancellation] CancellationToken token                               = default );
    ValueTask<ErrorOrResult<TSelf>>           Get( NpgsqlConnection                                                   connection, NpgsqlTransaction? transaction, RecordID<TSelf>?                  id,         CancellationToken                          token                               = default );
    ValueTask<ErrorOrResult<TSelf>>           Get( NpgsqlConnection                                                   connection, NpgsqlTransaction? transaction, RecordID<TSelf>                   id,         CancellationToken                          token                               = default );
    ValueTask<ErrorOrResult<TSelf>>           Get<T>( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, string                            columnName, T?                                         value,      CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           Get( NpgsqlConnection                                                   connection, NpgsqlTransaction? transaction, bool                              matchAll,   PostgresParameters                         parameters, CancellationToken token = default );
    ValueTask                                 Update( TSelf                                                           record,     CancellationToken  token                                                                 = default );
    ValueTask                                 Update( IEnumerable<TSelf>                                              records,    CancellationToken  token                                                                 = default );
    ValueTask                                 Update( ImmutableArray<TSelf>                                           records,    CancellationToken  token                                                                 = default );
    ValueTask                                 Update( IAsyncEnumerable<TSelf>                                         records,    CancellationToken  token                                                                 = default );
    ValueTask                                 Update( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, ImmutableArray<TSelf>   records, CancellationToken token = default );
    ValueTask                                 Update( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, IEnumerable<TSelf>      records, CancellationToken token = default );
    ValueTask                                 Update( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, IAsyncEnumerable<TSelf> records, CancellationToken token = default );
    ValueTask                                 Update( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, TSelf                   record,  CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           Next( RecordPair<TSelf>                                                 pair,       CancellationToken  token                                                        = default );
    ValueTask<ErrorOrResult<TSelf>>           Next( NpgsqlConnection                                                  connection, NpgsqlTransaction? transaction, RecordPair<TSelf> pair, CancellationToken token = default );
    ValueTask<Guid?>                          NextID( RecordPair<TSelf>                                               pair,       CancellationToken  token                                                        = default );
    ValueTask<Guid?>                          NextID( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, RecordPair<TSelf> pair, CancellationToken token = default );
    ValueTask<IEnumerable<RecordPair<TSelf>>> SortedIDs( CancellationToken                                            token                                                               = default );
    ValueTask<IEnumerable<RecordPair<TSelf>>> SortedIDs( NpgsqlConnection                                             connection, NpgsqlTransaction? transaction, CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           First( CancellationToken                                                token                                                               = default );
    ValueTask<ErrorOrResult<TSelf>>           First( NpgsqlConnection                                                 connection, NpgsqlTransaction? transaction, CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           FirstOrDefault( CancellationToken                                       token                                                               = default );
    ValueTask<ErrorOrResult<TSelf>>           FirstOrDefault( NpgsqlConnection                                        connection, NpgsqlTransaction? transaction, CancellationToken token = default );
    ValueTask                                 Delete( TSelf                                                           record,     CancellationToken  token                                                                             = default );
    ValueTask                                 Delete( IEnumerable<TSelf>                                              records,    CancellationToken  token                                                                             = default );
    ValueTask                                 Delete( IAsyncEnumerable<TSelf>                                         records,    CancellationToken  token                                                                             = default );
    ValueTask                                 Delete( RecordID<TSelf>                                                 id,         CancellationToken  token                                                                             = default );
    ValueTask                                 Delete( IEnumerable<RecordID<TSelf>>                                    ids,        CancellationToken  token                                                                             = default );
    ValueTask                                 Delete( IAsyncEnumerable<RecordID<TSelf>>                               ids,        CancellationToken  token                                                                             = default );
    ValueTask                                 Delete( bool                                                            matchAll,   PostgresParameters parameters,  CancellationToken                 token                              = default );
    ValueTask                                 Delete( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, TSelf                             record,   CancellationToken  token = default );
    ValueTask                                 Delete( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, IEnumerable<TSelf>                records,  CancellationToken  token = default );
    ValueTask                                 Delete( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, IAsyncEnumerable<TSelf>           records,  CancellationToken  token = default );
    ValueTask                                 Delete( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, IAsyncEnumerable<RecordID<TSelf>> ids,      CancellationToken  token = default );
    ValueTask                                 Delete( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, RecordID<TSelf>                   id,       CancellationToken  token = default );
    ValueTask                                 Delete( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, IEnumerable<RecordID<TSelf>>      ids,      CancellationToken  token = default );
    ValueTask                                 Delete( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, bool                              matchAll, PostgresParameters parameters, CancellationToken token );
    ValueTask<ErrorOrResult<TSelf>>           Single( RecordID<TSelf>                                                 id,         CancellationToken  token                                                                                          = default );
    ValueTask<ErrorOrResult<TSelf>>           Single( string                                                          sql,        PostgresParameters parameters,  CancellationToken token                                                           = default );
    ValueTask<ErrorOrResult<TSelf>>           Single( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, RecordID<TSelf>   id,      CancellationToken  token                               = default );
    ValueTask<ErrorOrResult<TSelf>>           Single( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, string            sql,     PostgresParameters parameters, CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           Single( NpgsqlConnection                                                connection, NpgsqlTransaction? transaction, SqlCommand<TSelf> command, CancellationToken  token = default );
    ValueTask<ErrorOrResult<TSelf>>           SingleOrDefault( RecordID<TSelf>                                        id,         CancellationToken  token                                                                                          = default );
    ValueTask<ErrorOrResult<TSelf>>           SingleOrDefault( string                                                 sql,        PostgresParameters parameters,  CancellationToken token                                                           = default );
    ValueTask<ErrorOrResult<TSelf>>           SingleOrDefault( NpgsqlConnection                                       connection, NpgsqlTransaction? transaction, RecordID<TSelf>   id,      CancellationToken  token                               = default );
    ValueTask<ErrorOrResult<TSelf>>           SingleOrDefault( NpgsqlConnection                                       connection, NpgsqlTransaction? transaction, string            sql,     PostgresParameters parameters, CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           SingleOrDefault( NpgsqlConnection                                       connection, NpgsqlTransaction? transaction, SqlCommand<TSelf> command, CancellationToken  token = default );
    ValueTask<ImmutableArray<TSelf>>          Insert( ReadOnlyMemory<TSelf>                                           records,    CancellationToken  token                                                                                                                                                     = default );
    ValueTask<ImmutableArray<TSelf>>          Insert( ImmutableArray<TSelf>                                           records,    CancellationToken  token                                                                                                                                                     = default );
    ValueTask<ImmutableArray<TSelf>>          Insert( IEnumerable<TSelf>                                              records,    CancellationToken  token                                                                                                                                                     = default );
    IAsyncEnumerable<TSelf>                   Insert( IAsyncEnumerable<TSelf>                                         records,    CancellationToken  token                                                                                                                                                     = default );
    ValueTask<TSelf>                          Insert( TSelf                                                           record,     CancellationToken  token                                                                                                                                                     = default );
    ValueTask<ImmutableArray<TSelf>>          Insert( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, IEnumerable<TSelf>      records, [EnumeratorCancellation] CancellationToken token                                                            = default );
    ValueTask<ImmutableArray<TSelf>>          Insert( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, ReadOnlyMemory<TSelf>   records, [EnumeratorCancellation] CancellationToken token                                                            = default );
    ValueTask<ImmutableArray<TSelf>>          Insert( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, ImmutableArray<TSelf>   records, [EnumeratorCancellation] CancellationToken token                                                            = default );
    IAsyncEnumerable<TSelf>                   Insert( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, IAsyncEnumerable<TSelf> records, [EnumeratorCancellation] CancellationToken token                                                            = default );
    ValueTask<TSelf>                          Insert( NpgsqlConnection                                                connection, NpgsqlTransaction  transaction, TSelf                   record,  CancellationToken                          token                                                            = default );
    ValueTask<ErrorOrResult<TSelf>>           TryInsert( NpgsqlConnection                                             connection, NpgsqlTransaction  transaction, TSelf                   record,  bool                                       matchAll, PostgresParameters parameters, CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           InsertOrUpdate( NpgsqlConnection                                        connection, NpgsqlTransaction  transaction, TSelf                   record,  bool                                       matchAll, PostgresParameters parameters, CancellationToken token = default );
    ValueTask<ErrorOrResult<TSelf>>           Random( CancellationToken                                               token                                                                                                                                                                                                                    = default );
    IAsyncEnumerable<TSelf>                   Random( int                                                             count,      [EnumeratorCancellation] CancellationToken token                                                                                                                                                             = default );
    IAsyncEnumerable<TSelf>                   Random( UserRecord                                                      user,       int                                        count,       [EnumeratorCancellation] CancellationToken token                                                                                                     = default );
    ValueTask<ErrorOrResult<TSelf>>           Random( NpgsqlConnection                                                connection, NpgsqlTransaction?                         transaction, CancellationToken                          token                                                                                                     = default );
    IAsyncEnumerable<TSelf>                   Random( NpgsqlConnection                                                connection, NpgsqlTransaction?                         transaction, UserRecord                                 user,  int                                        count, [EnumeratorCancellation] CancellationToken token = default );
    IAsyncEnumerable<TSelf>                   Random( NpgsqlConnection                                                connection, NpgsqlTransaction?                         transaction, int                                        count, [EnumeratorCancellation] CancellationToken token = default );
}
